<a href="https://colab.research.google.com/github/shirishbahirat/artificial-intelligence/blob/master/taxi_openai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import gym
import numpy as np

Possible Actions  down (0), up (1), right (2), left (3), pick-up (4), and drop-off (5)

In [0]:
env = gym.make("Taxi-v2")
state = env.reset()

In [0]:
print(state)
env.render()

441
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [0]:
n_states = env.observation_space.n
n_actions = env.action_space.n

How good does behaving completely random do?

In [0]:
state = env.reset()
counter = 0
g = 0
reward = None
while reward != 20:
    state, reward, done, info = env.step(env.action_space.sample())
    counter += 1
    g += reward
print("Solved in {} Steps with a total reward of {}".format(counter,g))

Solved in 2059 Steps with a total reward of -8149


Let's look at just one episode and see how the Q values change after each step using the formula below

In [0]:
Q = np.zeros([n_states, n_actions])

# This multidimensional array will keep a history of our Q-Values for all states
Q_hist = np.zeros([n_states, n_actions, 0])


episodes = 1
G = 0
alpha = 0.618

for episode in range(1,episodes+1):
    done = False
    G, reward = 0,0
    state = env.reset()
    firstState = state
    print("Initial State = {}".format(state))
    while reward != 20:
        action = np.argmax(Q[state]) 
        state2, reward, done, info = env.step(action)
        Q[state,action] += alpha * (reward + np.max(Q[state2]) - Q[state,action]) 
        G += reward
        state = state2
        
        #This will keep a history of Q Values in a multi dimensional array
        Q_hist = np.dstack((Q_hist, Q))
finalState = state
print("Final State = {}".format(finalState))


Initial State = 203
Final State = 475



Let's look at the first step!![alt text](qlearn.png)

In [0]:
print(firstState)
Q_hist[firstState,:,0]

203


array([-0.618,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ])

In [0]:
Q_hist.shape

(500, 6, 519)

In [0]:
print(finalState)
Q_hist[finalState,:,Q_hist.shape[2]-1]

475


array([0., 0., 0., 0., 0., 0.])

In [0]:
np.argmax(Q_hist[:,:,Q_hist.shape[2]-2], axis = 0)

array([0, 0, 0, 0, 0, 0])

In [0]:
episodes = 2000
rewardTracker = []

G = 0
alpha = 0.618

for episode in range(1,episodes+1):
    done = False
    G, reward = 0,0
    state = env.reset()
    while done != True:
        action = np.argmax(Q[state]) 
        state2, reward, done, info = env.step(action) 
        Q[state,action] += alpha * ((reward + (np.max(Q[state2]))  - Q[state,action]))
        G += reward
        state = state2
    
    if episode % 100 == 0:
        print('Episode {} Total Reward: {}'.format(episode,G))

Episode 100 Total Reward: -102
Episode 200 Total Reward: -130
Episode 300 Total Reward: 12
Episode 400 Total Reward: 8
Episode 500 Total Reward: 10
Episode 600 Total Reward: 7
Episode 700 Total Reward: 14
Episode 800 Total Reward: 7
Episode 900 Total Reward: 11
Episode 1000 Total Reward: 9
Episode 1100 Total Reward: 10
Episode 1200 Total Reward: 8
Episode 1300 Total Reward: 9
Episode 1400 Total Reward: 4
Episode 1500 Total Reward: 8
Episode 1600 Total Reward: 11
Episode 1700 Total Reward: 11
Episode 1800 Total Reward: 6
Episode 1900 Total Reward: 8
Episode 2000 Total Reward: 5


In [0]:
state = env.reset()
done = None

while done != True:
    # We simply take the action with the highest Q Value
    action = np.argmax(Q[state])
    state, reward, done, info = env.step(action)
    env.render()

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : |_: |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : : : : |
| : : :_: |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : : :_: |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : :_: : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| :_: : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R:_| : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Dropoff)
